kind: ConfigMap
apiVersion: v1
metadata:
  name: weather-app-config
data:
  config.json: |
    {
      "port": "8080",
      "remote_host": "https://api.coingecko.com/api/v3/simple/vs_currencies=usd&price?ids="
    }